# Generated by Django 4.2 on 2025-06-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(null=True, upload_to='movie_images'),
        ),
    ]
